### ISSUE TITLE
Thanks. Have you experienced any app-crashes on font set?

### ISSUE THREAD

**Issue by NotFlawffles** [NotFlawffles/termux-nerd-installer#2]
Thanks. Have you experienced any app-crashes on font set?

_Originally posted by @Anonymous2716 in https://github.com/NotFlawffles/termux-nerd-installer/issues/1#issuecomment-1598830126_

fixed.

**Comment by Anonymous2716** [comment]
I reported the issue to Termux and here is what I got.

https://github.com/termux/termux-app/issues/3473#issuecomment-1600400320

**Comment by NotFlawffles** [comment]
> I reported the issue to Termux and here is what I got.
> 
> [termux/termux-app#3473 (comment)](https://github.com/termux/termux-app/issues/3473#issuecomment-1600400320)

yes i knew what was the issue, i fixed it now, you will no longer get crashes on font set

**Comment by Anonymous2716** [comment]
Thanks.
