### ISSUE TITLE
Listing available fonts

### ISSUE THREAD

**Issue by Lockszmith-GH** [NotFlawffles/termux-nerd-installer#5]
Let me know what type of info you need.

Running termux on a OnePlus phone.
My shell is nushell.

After making the tool, everything works. I managed to install and set the font of my choice.

Listing available fonts, however, does indeed what it is supposed to, except each line is VERY VERY long, padded with whitespace. (I captured it with `less`)
This makes the output unreadable.

**Comment by Lockszmith-GH** [comment]
`termux-nerd-installer list available | wc -L` returned `6360`

**Comment by MorganJBradford** [comment]
@Lockszmith-GH I'll take a look if I get the chance. In the meantime you can output the font list into a file. I just ran the following (font is my alias to the path):

"font list available >> fonts.txt"

This will output the list into a file.

**Comment by Lockszmith-GH** [comment]
Yes, that's what I did. Just wanted to let you know about the issue.

**Comment by MorganJBradford** [comment]
@Lockszmith-GH I'm actually just a user, but thank you! lol. I just submitted a PR.
